# Generated by Django 3.0.2 on 2020-02-20 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam', models.CharField(choices=[('Midterm', 'Midterm'), ('Mid_Makeup', 'Mid_Makeup'), ('Final', 'Final'), ('Final_Makeup', 'Final_Makeup')], default='Midterm', max_length=15, null=True, verbose_name='Sınav Seçimi')),
                ('ydl', models.CharField(choices=[('183', '183'), ('184', '184'), ('185', '185'), ('186', '186')], max_length=3, null=True, verbose_name='YDL183,184,etc.')),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(blank=True, max_length=9, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Yıl',
                'verbose_name_plural': 'Yıllar',
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(choices=[('FALL', 'Güz'), ('SPRING', 'Bahar')], max_length=7, null=True)),
                ('year', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='questions.Year')),
            ],
            options={
                'verbose_name': 'Dönem',
                'verbose_name_plural': 'Dönemler',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(blank=True, default='', max_length=400, verbose_name='Soru')),
                ('option1', models.CharField(blank=True, default='', max_length=200, verbose_name='1.Seçenek')),
                ('option2', models.CharField(blank=True, default='', max_length=200, verbose_name='2.Seçenek')),
                ('option3', models.CharField(blank=True, default='', max_length=200, verbose_name='3.Seçenek')),
                ('option4', models.CharField(blank=True, default='', max_length=200, verbose_name='4.Seçenek')),
                ('columns', models.CharField(choices=[('1', '1 sütun'), ('2', '2 sütun'), ('4', '4 sütun')], default='1', max_length=1)),
                ('exam_title', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='examfk', to='questions.Exam')),
            ],
        ),
        migrations.AddField(
            model_name='exam',
            name='semester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='questions.Semester'),
        ),
        migrations.CreateModel(
            name='AnswerKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_a', models.CharField(blank=True, default='', max_length=25, verbose_name='A Kitapçığı Cevapları')),
                ('answer_b', models.CharField(blank=True, default='', max_length=25, verbose_name='B Kitapçığı Cevapları')),
                ('get_exam', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='examfk2', to='questions.Exam')),
            ],
        ),
    ]
