# Generated by Django 3.0.2 on 2020-02-20 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerkey',
            name='answer_a',
            field=models.CharField(default='', max_length=25, verbose_name='A Kitapçığı Cevapları'),
        ),
        migrations.AlterField(
            model_name='answerkey',
            name='answer_b',
            field=models.CharField(default='', max_length=25, verbose_name='B Kitapçığı Cevapları'),
        ),
    ]
