# Generated by Django 3.0.2 on 2020-02-25 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_question_spacer_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='spacer_field',
        ),
    ]
