# Generated by Django 3.0.2 on 2020-03-04 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_auto_20200303_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='session',
            field=models.CharField(choices=[('1', '1. Oturum'), ('2', '2. Oturum')], max_length=1, null=True, verbose_name='Oturum'),
        ),
    ]
