# Generated by Django 3.0.2 on 2020-03-25 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_exam_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.TextField(blank=True, default='', max_length=4000, verbose_name='Soru'),
        ),
    ]
