# Generated by Django 3.0.2 on 2020-03-25 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0008_auto_20200325_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
