# Generated by Django 3.0.2 on 2022-03-29 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0010_auto_20220329_0702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='option1',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='1.Seçenek'),
        ),
        migrations.AlterField(
            model_name='question',
            name='option2',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='2.Seçenek'),
        ),
        migrations.AlterField(
            model_name='question',
            name='option3',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='3.Seçenek'),
        ),
        migrations.AlterField(
            model_name='question',
            name='option4',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='4.Seçenek'),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_temp',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='GeçiciSeçenek'),
        ),
    ]
