# Generated by Django 3.0.2 on 2022-05-08 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0011_auto_20220329_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='exam',
            field=models.CharField(choices=[('Midterm', 'Midterm'), ('Mid_Makeup', 'Midterm Makeup'), ('Final', 'Final'), ('Final_Makeup', 'Final_Makeup')], default='Midterm', max_length=15, null=True, verbose_name='Sınav Seçimi'),
        ),
    ]
