# Generated by Django 3.0.2 on 2022-05-08 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0012_auto_20220508_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='exam',
            field=models.CharField(choices=[('Midterm', 'Midterm'), ('Midterm Makeup', 'Midterm Makeup'), ('Final', 'Final'), ('Final Makeup', 'Final_Makeup')], default='Midterm', max_length=15, null=True, verbose_name='Sınav Seçimi'),
        ),
    ]
