# Generated by Django 3.0.2 on 2022-05-10 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0013_auto_20220508_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='row_height',
            field=models.CharField(choices=[('1', '1 Satır'), ('2', '2 Satır'), ('3', '3 Satır')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='exam',
            name='exam',
            field=models.CharField(choices=[('Midterm', 'Midterm'), ('Midterm Makeup', 'Midterm_Makeup'), ('Final', 'Final'), ('Final Makeup', 'Final_Makeup')], default='Midterm', max_length=15, null=True, verbose_name='Sınav Seçimi'),
        ),
        migrations.AlterField(
            model_name='question',
            name='columns',
            field=models.CharField(choices=[('1', '1 sütun'), ('2', '2 sütun'), ('4', '4 sütun')], default='2', max_length=1),
        ),
    ]
