# Generated by Django 3.0.2 on 2022-05-13 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0014_auto_20220510_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='right_logo',
            field=models.CharField(choices=[('QR', 'QR Kod'), ('LOGO', 'Logo')], max_length=4, null=True, verbose_name='Sağ taraftaki logo boşluğu QR kod veya Logo'),
        ),
    ]
