# Generated by Django 3.0.2 on 2022-05-13 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0015_exam_right_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='right_logo',
            field=models.CharField(choices=[('QR', 'QR Kod'), ('LOGO', 'Logo')], max_length=4, null=True, verbose_name='Sağ üstteki boşluk: QR kod veya Logo'),
        ),
    ]
